<a href="https://colab.research.google.com/github/borjalasalles/Pytorch-Tutorial-Codemy/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch
import numpy as np

In [3]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.8081,  1.3312,  1.2536, -0.3958],
        [-2.3419, -0.2378,  1.5370, -0.6330],
        [ 1.2720, -0.5196,  0.0250,  0.7642]])

In [6]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
tensor_3d.dtype

torch.float32

In [8]:
np1 = np.random.rand(3,4)
np1

array([[0.9579899 , 0.59786259, 0.83368455, 0.11172089],
       [0.00647438, 0.36834961, 0.27698072, 0.65744457],
       [0.95880693, 0.77220036, 0.86706144, 0.81492508]])

In [9]:
# Create a tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9580, 0.5979, 0.8337, 0.1117],
        [0.0065, 0.3683, 0.2770, 0.6574],
        [0.9588, 0.7722, 0.8671, 0.8149]], dtype=torch.float64)

In [18]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

print(tensor_a + tensor_b)
print(tensor_a - tensor_b)
print(tensor_a * tensor_b)
print(tensor_b / tensor_a)
print(f'Remainder:{tensor_b % tensor_a}')
print(f'INT Multiplication:{tensor_b // tensor_a}')
print(f'Power:{torch.pow(tensor_a, tensor_b)}')

tensor([ 6,  8, 10, 12])
tensor([-4, -4, -4, -4])
tensor([ 5, 12, 21, 32])
tensor([5.0000, 3.0000, 2.3333, 2.0000])
Remainder:tensor([0, 0, 1, 0])
INT Multiplication:tensor([5, 3, 2, 2])
Power:tensor([    1,    64,  2187, 65536])


In [19]:
# Reassingment
# long way --- tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])